name: Run tests without Docker 

on:
  workflow_dispatch: 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Install python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run tests initially
      run: |
        pytest -s -v

    - name: Re-run failed tests
      if: failure()
      run: |
        pytest --last-failed -s -v
